language: node_js

node_js:
  - '7'


branches:
  only:
  - master
  - develop


before_script:
    - npm install -g angular-cli
    - npm install -g karma
    - npm install
    - ng build



script: karma start config/karma.conf.js --single-run
