sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - 10
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
jobs:
    include:
        - stage: "Lint"
          name: "Lint"
          script: npm run lint
        - stage: "Unit tests"
          name: "Unit tests"
          script: npm run test_ci
        - stage: "e2e tests"
          name: "e2e tests"
          script: npm run e2e
